# Language Dictionary
LANGUAGES = {
    'en': {
        'page_title': 'Polymarket Signal Analysis',
        'title': '📊 Polymarket Signal Analysis',
        'project': '**Project**: Empirical Detection of Unusual Odds Movements',
        'current_stage': '**Current Stage**: Data Visualization Phase',
        'config_options': '⚙️ Configuration Options',
        'select_market': 'Select Market',
        'data_view': 'Data View',
        'metadata_view': 'Market Metadata',
        'timeseries_view': 'Time Series Data',
        'trade_view': 'Trade Data',
        'anomaly_detection': '🔍 Anomaly Detection',
        'pattern_a': 'Pattern A: Front-running/Insider Trading Detection',
        'pattern_b': 'Pattern B: Arbitrage Opportunity Detection',
        'under_development': '🚧 Under Development...',
        'pattern_a_rules': '''**Detection Rules**:
        - Price deviation > Z-Score threshold
        - Volume spike''',
        'pattern_b_rules': '''**Detection Rules**:
        - |Price(Yes) + Price(No) - 1| > threshold
        - Duration > N minutes''',
        'market_info': '📈 Market Information',
        'market_id': 'Market ID',
        'volume_24hr': '24h Volume',
        'liquidity': 'Liquidity',
        'question': '**Question**',
        'end_date': '**End Date**',
        'error_metadata': 'Unable to load market metadata. Please check data file path.',
        'error_file_not_found': 'Market metadata file not found',
        'all_markets': '📋 All Market Metadata',
        'total_markets': 'Total Markets',
        'total_volume': 'Total Volume',
        'avg_liquidity': 'Avg Liquidity',
        'timeseries_data': '📊 Market Time Series Data',
        'data_points': 'Data Points',
        'time_range': 'Time Range',
        'avg_midpoint': 'Avg Midpoint',
        'price_chart': 'Price Chart',
        'price_trend': 'Price Trend',
        'order_depth': 'Order Depth',
        'yes_midpoint': 'YES Midpoint',
        'no_midpoint': 'NO Midpoint',
        'bid_depth': 'Bid Depth',
        'ask_depth': 'Ask Depth',
        'data_details': 'Data Details',
        'time': 'Time',
        'midpoint': 'Midpoint',
        'best_bid': 'Best Bid',
        'best_ask': 'Best Ask',
        'spread': 'Spread',
        'bid_depth_top5': 'Bid Depth Top5',
        'ask_depth_top5': 'Ask Depth Top5',
        'warning_no_data': 'No YES contract time series data found for market',
        'trade_data': '💹 Market Trade Data',
        'warning_no_trade_data': 'No YES contract trade data found for market',
        'total_trades': 'Total Trades',
        'total_amount': 'Total Amount',
        'avg_price': 'Avg Price',
        'volume_distribution': 'Volume Distribution',
        'buy_sell_volume': 'Buy/Sell Volume',
        'buy': 'Buy',
        'sell': 'Sell',
        'trade_records': 'Trade Records',
        'page': 'Page',
        'side': 'Side',
        'price': 'Price',
        'size': 'Size',
        'amount': 'Amount',
        'showing_records': 'Showing',
        'to': 'to',
        'of': 'of',
        'records': 'records',
        'total': 'total',
        'footer': 'CS6290 Group Project - Polymarket Signal Analysis',
        'language': 'Language',
        'select_anomaly_type': 'Select Anomaly Detection Type',
        'polymarket_anomaly': 'Polymarket Anomaly Detection',
        'sniper_detection': 'Sniper Detection',
        'no_anomaly_data': 'No anomaly detection data found',
        'anomaly_statistics': 'Anomaly Statistics',
        'anomaly_count': 'Number of Anomaly Events',
        'avg_duration': 'Average Duration (minutes)',
        'max_stress_score': 'Maximum Stress Score',
        'anomaly_time_distribution': 'Anomaly Time Distribution',
        'anomaly_events_cards': 'Anomaly Event Cards',
        'market_stress_anomaly': 'Market Stress Anomaly Event',
        'start_time': 'Start Time:',
        'end_time': 'End Time:',
        'duration': 'Duration:',
        'total_amount': 'Total Amount:',
        'peak_stress_score': 'Peak Stress Score:',
        'severe_anomaly': 'Severe Anomaly',
        'moderate_anomaly': 'Moderate Anomaly',
        'mild_anomaly': 'Mild Anomaly',
        'view_details': 'View Details',
        'stress_score_components': 'Stress Score Components',
        'activity_component': 'Activity Component',
        'liquidity_component': 'Liquidity Component',
        'price_component': 'Price Component',
        'market_state_indicators': 'Market State Indicators',
        'max_price_change': 'Maximum Price Change',
        'max_spread': 'Maximum Spread',
        'min_total_depth': 'Minimum Total Depth',
        'dominant_driver': 'Dominant Driver',
        'dominant_factor': 'Dominant Factor:',
        'trading_activity': 'Trading Activity',
        'liquidity_change': 'Liquidity Change',
        'price_dislocation': 'Price Dislocation',
        'mixed_factors': 'Mixed Factors',
        'sniper_statistics': 'Sniper Statistics',
        'sniper_count': 'Number of Sniper Candidates',
        'avg_anomaly_score': 'Average Anomaly Score',
        'verified_cases_count': 'Number of Verified Cases',
        'sniper_score_distribution': 'Sniper Score Distribution',
        'frequency': 'Frequency',
        'verified_sniper_cases': 'Verified Sniper Cases',
        'sniper_attack_case': 'Sniper Attack Case',
        'case_rank': 'Case Rank:',
        'session_id': 'Session ID:',
        'duration_seconds': 'Duration:',
        'profit': 'Profit:',
        'profit_positive': 'Profit',
        'profit_negative': 'Loss',
        'trade_details': 'Trade Details',
        'buy_operation': 'Buy Operation:',
        'sell_operation': 'Sell Operation:',
        'tx_hash': 'Transaction Hash:',
        'attack_window_visualization': 'Attack Window Visualization',
        'image_not_found': 'Image file not found:',
        'sniper_candidates_list': 'Sniper Candidates List',
        'sniper_candidate': 'Sniper Candidate',
        'suspicious_rank': 'Suspicious Rank:',
        'num_trades': 'Number of Trades:',
        'total_volume': 'Total Volume:',
        'high_risk': 'High Risk',
        'medium_risk': 'Medium Risk',
        'low_risk': 'Low Risk',
        'amount_label': 'Amount:',
        'price_label': 'Price:',
        'time_label': 'Time:',
        'date_label': 'Date:',
        'minutes_unit': 'minutes',
        'seconds_unit': 'seconds',
        'candidate_label': 'Candidate',
        'previous': 'Previous',
        'next': 'Next',
        'layer_1_title': 'Layer 1: Market Overview',
        'layer_2_title': 'Layer 2: Single Market Events',
        'layer_3_title': 'Layer 3: Single Event Diagnostics',
        'top_stress_events': 'Top Stress Events',
        'market_health_comparison': 'Market Health Comparison',
        'event_attribution_distribution': 'Event Attribution Distribution',
        'event_bubble_chart': 'Event Bubble Chart',
        'event_details_list': 'Event Details List',
        'composite_stress_score': 'Composite Stress Score',
        'trading_activity_chart': 'Trading Activity',
        'liquidity_status_chart': 'Liquidity Status',
        'price_trend_chart': 'Price Trend',
        'market_name': 'Market Name',
        'occurrence_time': 'Occurrence Time',
        'duration': 'Duration',
        'stress_events_count': 'Stress Events Count',
        'select_view_layer': 'Select View Layer',
        'market_overview': 'Market Overview',
        'single_market_events': 'Single Market Events',
        'single_event_diagnostics': 'Single Event Diagnostics',
        'select_event': 'Select Event',
        'anomaly_threshold': 'Anomaly Threshold',
        'event_interval': 'Event Interval'
    },
    'zh': {
        'page_title': 'Polymarket 信号分析',
        'title': '📊 Polymarket 信号分析',
        'project': '**项目**: 实证检测异常赔率变动',
        'current_stage': '**当前阶段**: 数据展示阶段',
        'config_options': '⚙️ 配置选项',
        'select_market': '选择市场',
        'data_view': '数据视图',
        'metadata_view': '市场元数据',
        'timeseries_view': '时间序列数据',
        'trade_view': '交易数据',
        'anomaly_detection': '🔍 异常检测',
        'pattern_a': '模式A: 前运行/内幕交易检测',
        'pattern_b': '模式B: 套利机会检测',
        'under_development': '🚧 功能开发中...',
        'pattern_a_rules': '''**检测规则**:
        - 价格偏离 > Z-Score阈值
        - 交易量突增''',
        'pattern_b_rules': '''**检测规则**:
        - |Price(Yes) + Price(No) - 1| > 阈值
        - 持续时间 > N分钟''',
        'market_info': '📈 市场信息',
        'market_id': '市场ID',
        'volume_24hr': '24小时交易量',
        'liquidity': '流动性',
        'question': '**问题描述**',
        'end_date': '**结束日期**',
        'error_metadata': '无法加载市场元数据，请检查数据文件路径。',
        'error_file_not_found': '市场元数据文件不存在',
        'all_markets': '📋 所有市场元数据',
        'total_markets': '市场总数',
        'total_volume': '总交易量',
        'avg_liquidity': '平均流动性',
        'timeseries_data': '📊 市场时间序列数据',
        'data_points': '数据点数量',
        'time_range': '时间范围',
        'avg_midpoint': '平均中间价',
        'price_chart': '价格走势图',
        'price_trend': '价格走势',
        'order_depth': '订单深度',
        'yes_midpoint': 'YES中间价',
        'no_midpoint': 'NO中间价',
        'bid_depth': '买单深度',
        'ask_depth': '卖单深度',
        'data_details': '数据详情',
        'time': '时间',
        'midpoint': '中间价',
        'best_bid': '最高买价',
        'best_ask': '最低卖价',
        'spread': '价差',
        'bid_depth_top5': '买单深度',
        'ask_depth_top5': '卖单深度',
        'warning_no_data': '未找到市场的YES合约时间序列数据',
        'trade_data': '💹 市场交易数据',
        'warning_no_trade_data': '未找到市场的YES合约交易数据',
        'total_trades': '总交易笔数',
        'total_amount': '总交易金额',
        'avg_price': '平均交易价格',
        'volume_distribution': '交易量分布',
        'buy_sell_volume': '买入/卖出交易量',
        'buy': '买入',
        'sell': '卖出',
        'trade_records': '交易记录',
        'page': '页码',
        'side': '方向',
        'price': '价格',
        'size': '数量',
        'amount': '金额',
        'showing_records': '显示',
        'to': '到',
        'of': '条记录，共',
        'records': '条',
        'total': '条',
        'footer': 'CS6290 小组项目 - Polymarket 信号分析',
        'language': '语言',
        'select_anomaly_type': '选择异常检测类型',
        'polymarket_anomaly': '多市场异常检测',
        'sniper_detection': '狙击手检测',
        'no_anomaly_data': '未找到异常检测数据',
        'anomaly_statistics': '异常统计',
        'anomaly_count': '异常事件数量',
        'avg_duration': '平均持续时间（分钟）',
        'max_stress_score': '最高压力分数',
        'anomaly_time_distribution': '异常时间分布',
        'anomaly_events_cards': '异常事件卡片',
        'market_stress_anomaly': '市场压力异常事件',
        'start_time': '开始时间:',
        'end_time': '结束时间:',
        'duration': '持续时间:',
        'peak_stress_score': '峰值压力分数:',
        'severe_anomaly': '严重异常',
        'moderate_anomaly': '中度异常',
        'mild_anomaly': '轻度异常',
        'view_details': '查看详细信息',
        'stress_score_components': '压力分数组件',
        'activity_component': '活跃度成分',
        'liquidity_component': '流动性成分',
        'price_component': '价格成分',
        'market_state_indicators': '市场状态指标',
        'max_price_change': '最大价格变化',
        'max_spread': '最大价差',
        'min_total_depth': '最小总深度',
        'dominant_driver': '主导驱动因素',
        'dominant_factor': '主导因素:',
        'trading_activity': '交易活跃度',
        'liquidity_change': '流动性变化',
        'price_dislocation': '价格错位',
        'mixed_factors': '混合因素',
        'sniper_statistics': '狙击手统计',
        'sniper_count': '狙击手候选数量',
        'avg_anomaly_score': '平均异常分数',
        'verified_cases_count': '已验证案例数量',
        'sniper_score_distribution': '狙击手分数分布',
        'frequency': '频率',
        'verified_sniper_cases': '已验证狙击手案例',
        'sniper_attack_case': '狙击手攻击案例',
        'case_rank': '案例排名:',
        'session_id': '会话ID:',
        'duration_seconds': '持续时间:',
        'profit': '利润:',
        'profit_positive': '盈利',
        'profit_negative': '亏损',
        'trade_details': '交易详情',
        'buy_operation': '买入操作:',
        'sell_operation': '卖出操作:',
        'tx_hash': '交易哈希:',
        'attack_window_visualization': '攻击窗口可视化',
        'image_not_found': '图片文件未找到:',
        'sniper_candidates_list': '狙击手候选列表',
        'sniper_candidate': '狙击手候选',
        'suspicious_rank': '可疑度排名:',
        'num_trades': '交易数量:',
        'total_volume': '总交易量:',
        'high_risk': '高风险',
        'medium_risk': '中风险',
        'low_risk': '低风险',
        'amount_label': '金额:',
        'price_label': '价格:',
        'time_label': '时间:',
        'date_label': '日期:',
        'minutes_unit': '分钟',
        'seconds_unit': '秒',
        'candidate_label': '候选',
        'previous': '上一页',
        'next': '下一页',
        'layer_1_title': '第一层：全市场宏观概览',
        'layer_2_title': '第二层：单市场事件汇总',
        'layer_3_title': '第三层：单事件微观诊断',
        'top_stress_events': 'Top压力事件排行榜',
        'market_health_comparison': '市场健康度对比',
        'event_attribution_distribution': '事件归因分布',
        'event_bubble_chart': '事件气泡图',
        'event_details_list': '事件详情列表',
        'composite_stress_score': '综合压力评分',
        'trading_activity_chart': '交易活跃度',
        'liquidity_status_chart': '流动性状态',
        'price_trend_chart': '价格走势',
        'market_name': '市场名称',
        'occurrence_time': '发生时间',
        'duration': '持续时间',
        'stress_events_count': '压力事件数量',
        'select_view_layer': '选择视图层级',
        'market_overview': '全市场概览',
        'single_market_events': '单市场事件',
        'single_event_diagnostics': '单事件诊断',
        'select_event': '选择事件',
        'anomaly_threshold': '异常阈值',
        'event_interval': '事件区间'
    }
}